#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Prepare and compare CryEngine Material Editor .mtl round-trip fixtures."""

import argparse
import json
import os
import shutil
import subprocess
import time
import xml.etree.ElementTree as ET

try:
    from _repo_path import add_repo_root
except ModuleNotFoundError:
    from tools._repo_path import add_repo_root

add_repo_root()

from tools.mtl_genmask_probe import KEEP, MTLMaskVariant, apply_mask_variant_to_mtl, default_mask_variants
from tools.mtl_schema_report import analyze_mtl_file


DEFAULT_SANDBOX_EXE = r"S:\Crytek\crytek\cryengine-57-lts\5.7.1\bin\win_x64\Sandbox.exe"
DEFAULT_GAMESDK_ROOT = r"S:\Crytek\crytek\cryengine-gamesdk-sample-project\5.7.1\gamesdk"
DEFAULT_CRYPROJECT = r"S:\Crytek\crytek\cryengine-gamesdk-sample-project\5.7.1\gamesdk.cryproject"
DEFAULT_MATERIAL_SUBDIR = "materials/codex_phase37_roundtrip"


def _write_base_mtl(path):
    root = ET.Element(
        "Material",
        MtlFlags="524288",
        Shader="Illum",
        GenMask="32",
        StringGenMask="%SUBSURFACE_SCATTERING",
        SurfaceType="mat_concrete",
        MatTemplate="",
        Diffuse="1,1,1",
        Specular="0.0030352699,0.0030352699,0.0030352699",
        Emissive="0,0,0",
        Shininess="10",
        Opacity="1",
        LayerAct="1",
    )
    textures = ET.SubElement(root, "Textures")
    ET.SubElement(textures, "Texture", Map="Diffuse", File="%ENGINE%/EngineAssets/Textures/white.dds")
    ET.SubElement(root, "PublicParams", SSSIndex="0", IndirectColor="0.25,0.25,0.25")
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)


def _material_game_name(game_root, mtl_path):
    rel_path = os.path.relpath(mtl_path, game_root).replace("\\", "/")
    return rel_path


def _variant_to_dict(variant):
    return {
        "slug": variant.slug,
        "description": variant.description,
        "gen_mask": variant.gen_mask,
        "string_gen_mask": variant.string_gen_mask,
    }


def _sandbox_script(cases, report_path, quit_after=True):
    payload = {
        "cases": [{"slug": case["slug"], "material_name": case["material_name"]} for case in cases],
        "report_path": report_path.replace("\\", "\\\\"),
        "quit_after": quit_after,
    }
    return f"""# Auto-generated by tools.material_editor_roundtrip.
import json
import traceback

import general
import material

payload = {json.dumps(payload, indent=2)}
results = []

for case in payload["cases"]:
    record = {{"slug": case["slug"], "material_name": case["material_name"], "success": False, "error": ""}}
    try:
        surface_type = material.get_property(case["material_name"], "Material Settings/Surface Type")
        material.set_property(case["material_name"], "Material Settings/Surface Type", surface_type)
        record["success"] = True
    except Exception as exc:
        record["error"] = str(exc)
        record["traceback"] = traceback.format_exc()
    results.append(record)

with open(payload["report_path"], "w") as f:
    json.dump({{"results": results}}, f, indent=2)

if all(record["success"] for record in results):
    general.set_result_to_success()
else:
    general.set_result_to_failure()

if payload["quit_after"]:
    general.run_console("quit")
"""


def prepare_roundtrip_fixtures(
    work_dir,
    game_root=DEFAULT_GAMESDK_ROOT,
    sandbox_exe=DEFAULT_SANDBOX_EXE,
    cryproject_path=DEFAULT_CRYPROJECT,
    material_subdir=DEFAULT_MATERIAL_SUBDIR,
    variants=None,
    quit_after=True,
):
    work_dir = os.path.abspath(work_dir)
    game_root = os.path.abspath(game_root)
    sandbox_exe = os.path.abspath(sandbox_exe)
    cryproject_path = os.path.abspath(cryproject_path) if cryproject_path else ""
    variants = variants or default_mask_variants()

    input_dir = os.path.join(work_dir, "input")
    os.makedirs(input_dir, exist_ok=True)
    editor_material_dir = os.path.join(game_root, material_subdir.replace("/", os.sep))
    os.makedirs(editor_material_dir, exist_ok=True)

    cases = []
    for variant in variants:
        base_name = f"Phase37_{variant.slug}.mtl"
        input_path = os.path.join(input_dir, base_name)
        staged_path = os.path.join(editor_material_dir, base_name)
        _write_base_mtl(input_path)
        apply_mask_variant_to_mtl(input_path, variant)
        shutil.copy2(input_path, staged_path)
        cases.append(
            {
                "slug": variant.slug,
                "description": variant.description,
                "variant": _variant_to_dict(variant),
                "input_path": input_path,
                "staged_path": staged_path,
                "material_name": _material_game_name(game_root, staged_path),
            }
        )

    sandbox_result_path = os.path.join(work_dir, "sandbox_roundtrip_result.json")
    sandbox_script_path = os.path.join(work_dir, "run_material_roundtrip.py")
    with open(sandbox_script_path, "w", encoding="utf-8") as f:
        f.write(_sandbox_script(cases, sandbox_result_path, quit_after=quit_after))

    launch_command = [
        sandbox_exe,
        "-project",
        cryproject_path,
        "/BatchMode",
        "/runpython",
        sandbox_script_path,
    ]
    sandbox_popen = {
        "executable": sandbox_exe,
        "args": [
            sandbox_script_path,
            "-project",
            cryproject_path,
            "/BatchMode",
            "/runpython",
        ],
        "strategy": "script_path_as_argv0",
    }
    sandbox_edcommand = {
        "executable": sandbox_exe,
        "args": [
            sandbox_exe,
            "-project",
            cryproject_path,
            "-edCommand",
            f"general.run_file '{sandbox_script_path}'",
        ],
        "strategy": "normal_editor_edCommand_run_file",
    }
    manifest = {
        "kind": "material_editor_roundtrip_fixture",
        "work_dir": work_dir,
        "game_root": game_root,
        "material_subdir": material_subdir,
        "editor_material_dir": editor_material_dir,
        "sandbox_exe": sandbox_exe,
        "cryproject_path": cryproject_path,
        "sandbox_script_path": sandbox_script_path,
        "sandbox_result_path": sandbox_result_path,
        "launch_command": launch_command,
        "sandbox_popen": sandbox_popen,
        "sandbox_edcommand": sandbox_edcommand,
        "cases": cases,
        "notes": [
            "Use sandbox_popen for automated runs so CryEdit.cpp sees the script path as the first non-flag argument.",
            "Use sandbox_edcommand to try a normal Editor launch without /BatchMode.",
            "launch_command is the human-readable Sandbox command, but normal shells may pass Sandbox.exe as argv0.",
            "After Sandbox exits, run the compare command against this manifest.",
        ],
    }
    manifest_path = os.path.join(work_dir, "material_editor_roundtrip_manifest.json")
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    manifest["manifest_path"] = manifest_path
    return manifest


def _material_by_location(report):
    return {material["location"]: material for material in report["materials"]}


def _dict_diff(before, after):
    keys = sorted(set(before) | set(after))
    changes = {}
    for key in keys:
        before_value = before.get(key, "")
        after_value = after.get(key, "")
        if before_value != after_value:
            changes[key] = {"before": before_value, "after": after_value}
    return changes


def compare_roundtrip_manifest(manifest_path):
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    cases = []
    changed_count = 0
    missing_after_count = 0
    for case in manifest.get("cases", []):
        input_path = case["input_path"]
        staged_path = case["staged_path"]
        case_report = {
            "slug": case["slug"],
            "input_path": input_path,
            "staged_path": staged_path,
            "exists_after": os.path.exists(staged_path),
            "changed": False,
            "material_changes": [],
        }
        if not os.path.exists(staged_path):
            missing_after_count += 1
            cases.append(case_report)
            continue

        before_file = analyze_mtl_file(input_path)
        after_file = analyze_mtl_file(staged_path)
        before_materials = _material_by_location(before_file)
        after_materials = _material_by_location(after_file)
        for location in sorted(set(before_materials) | set(after_materials)):
            before = before_materials.get(location, {})
            after = after_materials.get(location, {})
            changes = {
                "location": location,
                "attributes": _dict_diff(before.get("attributes", {}), after.get("attributes", {})),
                "public_params": _dict_diff(before.get("public_params", {}), after.get("public_params", {})),
                "tokens": {
                    "before": before.get("tokens", []),
                    "after": after.get("tokens", []),
                },
                "textures": {
                    "before": before.get("textures", []),
                    "after": after.get("textures", []),
                },
            }
            tokens_changed = changes["tokens"]["before"] != changes["tokens"]["after"]
            textures_changed = changes["textures"]["before"] != changes["textures"]["after"]
            if changes["attributes"] or changes["public_params"] or tokens_changed or textures_changed:
                case_report["material_changes"].append(changes)

        case_report["changed"] = bool(case_report["material_changes"])
        if case_report["changed"]:
            changed_count += 1
        cases.append(case_report)

    sandbox_result = {}
    sandbox_result_path = manifest.get("sandbox_result_path", "")
    if sandbox_result_path and os.path.exists(sandbox_result_path):
        with open(sandbox_result_path, "r", encoding="utf-8") as f:
            sandbox_result = json.load(f)

    return {
        "kind": "material_editor_roundtrip_compare",
        "manifest_path": os.path.abspath(manifest_path),
        "sandbox_result_path": sandbox_result_path,
        "sandbox_result": sandbox_result,
        "summary": {
            "case_count": len(cases),
            "changed_count": changed_count,
            "unchanged_count": len(cases) - changed_count - missing_after_count,
            "missing_after_count": missing_after_count,
            "sandbox_result_present": bool(sandbox_result),
        },
        "cases": cases,
    }


def _select_sandbox_launch(manifest, strategy):
    if strategy == "edcommand":
        launch = manifest.get("sandbox_edcommand", {})
        command = launch.get("args")
    elif strategy == "launch_command":
        launch = {"strategy": "launch_command"}
        command = manifest.get("launch_command")
    else:
        launch = manifest.get("sandbox_popen", {})
        command = launch.get("args")

    if not command:
        command = manifest["launch_command"]
    executable = launch.get("executable", command[0] if command else "")
    return command, executable, launch.get("strategy", strategy)


def run_sandbox_roundtrip(manifest_path, timeout_seconds=120, strategy="argv0"):
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    result_path = manifest.get("sandbox_result_path", "")
    if result_path:
        try:
            os.remove(result_path)
        except FileNotFoundError:
            pass

    command, executable, launch_strategy = _select_sandbox_launch(manifest, strategy)
    cwd = os.path.dirname(os.path.abspath(executable)) if executable else None
    process = subprocess.Popen(command, cwd=cwd, executable=executable or None)
    deadline = time.time() + timeout_seconds
    state = "timeout"
    while time.time() < deadline:
        if result_path and os.path.exists(result_path):
            state = "result"
            break
        if process.poll() is not None:
            state = "exited"
            break
        time.sleep(1)

    if process.poll() is None:
        process.kill()
        try:
            process.wait(timeout=10)
        except subprocess.TimeoutExpired:
            pass

    sandbox_result = {}
    if result_path and os.path.exists(result_path):
        with open(result_path, "r", encoding="utf-8") as f:
            sandbox_result = json.load(f)

    return {
        "kind": "material_editor_roundtrip_sandbox_run",
        "manifest_path": os.path.abspath(manifest_path),
        "command": command,
        "executable": executable,
        "launch_strategy": launch_strategy,
        "timeout_seconds": timeout_seconds,
        "state": state,
        "returncode": process.poll(),
        "result_path": result_path,
        "result_exists": bool(result_path and os.path.exists(result_path)),
        "sandbox_result": sandbox_result,
    }


def write_json(data, output_path):
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    return output_path


def main(argv=None):
    parser = argparse.ArgumentParser(description="Prepare or compare Material Editor .mtl round-trip fixtures.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    prepare = subparsers.add_parser("prepare", help="Create fixture materials and a Sandbox /runpython script")
    prepare.add_argument("--work-dir", required=True, help="Work directory for manifest and source copies")
    prepare.add_argument("--game-root", default=DEFAULT_GAMESDK_ROOT, help="CryEngine game root folder")
    prepare.add_argument("--sandbox", default=DEFAULT_SANDBOX_EXE, help="Path to Sandbox.exe")
    prepare.add_argument("--cryproject", default=DEFAULT_CRYPROJECT, help="Path to the .cryproject file")
    prepare.add_argument("--material-subdir", default=DEFAULT_MATERIAL_SUBDIR, help="Game-relative material staging folder")
    prepare.add_argument("--no-quit", action="store_true", help="Do not ask Sandbox to quit after script execution")
    prepare.add_argument("--output", default="", help="Optional manifest output path")

    compare = subparsers.add_parser("compare", help="Compare prepared source materials against editor-saved staged files")
    compare.add_argument("--manifest", required=True, help="Manifest from the prepare command")
    compare.add_argument("--output", default="", help="Optional JSON compare report path")

    run = subparsers.add_parser("run", help="Run Sandbox with the manifest launch command and wait for script output")
    run.add_argument("--manifest", required=True, help="Manifest from the prepare command")
    run.add_argument("--timeout", type=int, default=120, help="Seconds to wait for Sandbox script output")
    run.add_argument(
        "--strategy",
        choices=("argv0", "edcommand", "launch_command"),
        default="argv0",
        help="Sandbox launch strategy recorded in the manifest",
    )
    run.add_argument("--output", default="", help="Optional JSON run report path")

    args = parser.parse_args(argv)
    if args.command == "prepare":
        manifest = prepare_roundtrip_fixtures(
            args.work_dir,
            game_root=args.game_root,
            sandbox_exe=args.sandbox,
            cryproject_path=args.cryproject,
            material_subdir=args.material_subdir,
            quit_after=not args.no_quit,
        )
        output_path = args.output or manifest["manifest_path"]
        if output_path != manifest["manifest_path"]:
            write_json(manifest, output_path)
        print(f"manifest: {output_path}")
        print("launch_command:")
        print(" ".join(f'"{part}"' if " " in part else part for part in manifest["launch_command"]))
        return 0

    if args.command == "run":
        report = run_sandbox_roundtrip(args.manifest, timeout_seconds=args.timeout, strategy=args.strategy)
        output_path = args.output or os.path.join(os.path.dirname(os.path.abspath(args.manifest)), "material_editor_roundtrip_sandbox_run.json")
        write_json(report, output_path)
        print(f"report: {output_path}")
        print(json.dumps({key: report[key] for key in ("state", "returncode", "result_exists")}, indent=2))
        return 0 if report["result_exists"] else 1

    report = compare_roundtrip_manifest(args.manifest)
    output_path = args.output or os.path.join(os.path.dirname(os.path.abspath(args.manifest)), "material_editor_roundtrip_compare.json")
    write_json(report, output_path)
    print(f"report: {output_path}")
    print(json.dumps(report["summary"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
